# Estágio 1: Ambiente de Desenvolvimento
FROM node:22.11.0 AS dev
WORKDIR /app

# Instalação das dependências
COPY package.json package-lock.json ./
RUN npm install

# Copia o código fonte
COPY . .

# Começa o servidor
CMD ["npm", "run", "dev"]

# Estágio 2: Ambiente de Produção
FROM node:22.11.0-slim AS prod
WORKDIR /app

# Instalação das dependências de produção
COPY package.json package-lock.json ./
RUN npm install --only=production

# Copia o código fonte
COPY ./src ./src

# Expõe a porta 8080
EXPOSE 8080

# Inicia o servidor
CMD ["node", "./src/server.js"]